raise sphinx version to enable proper pdf build
opentelekomcloud-docs/docs-constraints pull request #5
Opened 2024-10-11 07:59 UTC by tischrei

2024-10-11 08:14 UTC, vladimirhasko submitted a review, later dismissed

2024-10-11 08:16 UTC, SebastianGode requested changes

2024-10-11 08:16 UTC, SebastianGode commented on constraints.txt
> +sphinx>=7.1.4
should be `sphinx>=7.4` see https://www.sphinx-doc.org/en/master/latex.html
![grafik](https://github.com/user-attachments/assets/cdadde1e-44e7-4633-9081-9045e8cb9f17)

2024-10-14 08:38 UTC, SebastianGode approved these changes

2024-10-14 09:13 UTC, tischrei commented
recheck

2024-10-14 09:16 UTC, closed without merging